### ISSUE TITLE
In load_db(), IOError: [Errno 2] No such file or directory: 'exac_data/forweb_cleaned_exac_r03_march16_z_data_pLI.txt.gz'

### ISSUE THREAD

**Issue by laurensvdwiel** [konradjk/exac_browser#241]
Hi ExaC team, 

When trying to build the mongodb database, following the steps provided on the page https://github.com/konradjk/exac_browser , I ran into a file not found error. The file in question is also not located in the link containing the data:  'http://broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz'

Output of the error:
```
> ~/exac/exac_env/bin/python ~/exac/exac_browser/manage.py load_db
Traceback (most recent call last):
  File "/root/exac/exac_browser/manage.py", line 60, in <module>
    manager.run()
  File "/root/exac/exac_env/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/root/exac/exac_env/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/root/exac/exac_env/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/root/exac/exac_browser/manage.py", line 17, in load_db
    exac.load_db()
  File "/root/exac/exac_browser/exac.py", line 359, in load_db
    procs = load_function()
  File "/root/exac/exac_browser/exac.py", line 191, in load_constraint_information
    with gzip.open(app.config['CONSTRAINT_FILE']) as constraint_file:
  File "/usr/local/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/local/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/root/exac/exac_browser/../exac_data/forweb_cleaned_exac_r03_march16_z_data_pLI.txt.gz'
```

**Comment by pontikos** [comment]
This file is in the downloads section of the website. I suggest you modify
the path to point to the location of your download.

**Comment by laurensvdwiel** [comment]
Are you referring to the files contained within : ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3/functional_gene_constraint/ ?

If so, the filenames are different. Hence the issue.

**Comment by vanya-antonov** [comment]
Hello Laurens,

I am trying to run Exac Browser locally and the main archive is missing
http://broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz

I was wondering, if you a copy of this archive by any chance... Thanks!

**Comment by laurensvdwiel** [comment]
Hi @vanya-antonov !

Wow, you replied to a thread from 2016! As I personally hate it when I myself find ancient threads with the same issues but no fixes. I do a have multiple copies of the files that are supposedly in `exac_browser.tar.gz`, but I am unsure as I untarred the archive so long ago.

Please let me know which files you require and I can send them to you through email (send me your email through DM), the backups I have are:
- release 0.3
- release 0.3.1

Please let me know if you want either of them.

As you may know, this project was phased into gnomad and I would not be surprised if support continues. Regardless, @konradjk this is an issue regarding the installation instructions of exac_browser,  it no longer works because the link http://broadinstitute.org/~konradk/exac_browser/ is no longer accessible. In the README.MD is concerns the following part:
```
wget http://broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz .
tar zxvf exac_browser.tar.gz
cd .. 
```

**Comment by vanya-antonov** [comment]
Hello @laurensvdwiel !

Thank you for the quick reply:) Actually, I think I was able to find all the required files here:
https://console.cloud.google.com/storage/browser/gcp-public-data--gnomad/legacy/exac_browser;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Anyway, I appreciate your response very much. Will see how it goes with running Exac after 7 years without support though.
