### ISSUE TITLE
IBD Exomes Browser - ConnectionFailure

### ISSUE THREAD

**Issue by pyrAmider** [konradjk/exac_browser#341]
After entering the string "NOD2" into the query field of https://ibd.broadinstitute.org/ and hitting Return, the following error was observed:

pymongo.errors.ConnectionFailure
ConnectionFailure: connection closed

Traceback (most recent call last)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1976, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1552, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1973, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1626, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1529, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1624, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/local/ibd2016meta/exac/exac_browser/exac.py", line 684, in awesome
db = get_db()
File "/local/ibd2016meta/exac/exac_browser/exac.py", line 658, in get_db
g.db_conn = connect_db()
File "/local/ibd2016meta/exac/exac_browser/exac.py", line 91, in connect_db
client = pymongo.MongoClient(host=app.config['DB_HOST'], port=app.config['DB_PORT'])
File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 369, in __init__
raise ConnectionFailure(str(e))
ConnectionFailure: connection closed
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by tomsing1** [comment]
This issue still persists. It also affects any of the example queries provided on the site.
The browser seems to be down?

**Comment by bw2** [comment]
This is fixed now.
